#-------------------------------
# Site Settings
title: joe-mccann.dev
logo: # You can add own logo. For example '/images/logo.png'.
author: Joe McCann
description: Full Stack Developer based in the Boston area.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Resume'
      url: '/resume/'

#-------------------------------
# Hero Settings
hero:
  hero__title: Hi there, my name's Joe. I'm a Full Stack Developer based in New England.
  hero__description: I'm a self-taught programmer and software enthusiast. About two years ago, I discovered a love of programming. I've since been building rewarding projects and git committing frequently. When I'm not debugging or writing specs, I enjoy playing guitar and bass, discovering new music, and running or hiking the trails of New England. Please feel free to check out the projects in my <a href="#portfolio">portfolio</a>.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__projects:
    - image: /images/chess.png
      title: Ruby Chess
      summary: A fully playable command line chess game programmed in pure Ruby.
      demo: <a href="https://replit.com/@joemccanndev/chess">replit.com/@joemccanndev/chess</a>
      repo: <a href="https://github.com/joe-mccann-dev/chess">github.com/joe-mccann-dev/chess</a>
      description:
        - Follows all major chess rules including check, checkmate, stalemate, en passant, castling, etc.
        - Utilizes object oriented programming principles.
        - Allows players to challenge another person or a simple AI.
        - Includes RSpec test suite.
    
    - image: /images/gembook.png
      title: Gembook
      summary: A social media site written in Ruby on Rails.
      demo: <a href="https://gembook.net">gembook.net</a>
      repo: <a href="https://github.com/joe-mccann-dev/gembook">github.com/joe-mccann-dev/gembook</a>
      description:
        - Authenticate via Devise or OAuth authentication.
        - Utilizes polymorphic associations (likeable and commentable).
        - Search for other users by name.
        - Friend/Unfriend other users. Post text content, images, or both. Comment on posts or other comments. Create a profile. Like posts and comments.
        - Includes RSpec test suite.

    - image: /images/private-events.png
      title: Private Events
      summary: Full Stack Ruby on Rails application. Create and attend events. RSVP and invite others to events.
      demo: <a href="https://private-events.net/">private-events.net</a>
      repo: <a href="https://github.com/joe-mccann-dev/private-events">github.com/joe-mccann-dev/private-events</a>
      description:
        - Harnesses the power of Rails' Active Record associations.
        - Sends multiple emails via Action Mailer and the SendGrid Heroku add-on.
        - Users can select one or multiple users to invite to an event.
        - Features live chat via Action Cable websockets. Chat in real-time on the "Members" page or an event page.
        - Includes RSpec test suite.

    - image: /images/raven-reservations.png
      title: Raven Reservations
      summary: Ruby on Rails flight booker. Book a one-way flight to a selection of airports with up to four passengers per booking.
      demo: <a href="https://raven-reservations.com/">raven-reservations.com</a>
      repo: <a href="https://github.com/joe-mccann-dev/odin-flight-booker">github.com/joe-mccann-dev/odin-flight-booker</a>
      description:
        - Showcases advanced form functionality utilizing nested attributes. 
        - Sends a confirmation email via Action Mailer and the SendGrid Heroku add-on.
        - Allows users to search for their booking via email or confirmation number.
        - Includes RSpec test suite.
      
#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com/joe_mccann_dev"}
- {icon: "ion-logo-linkedin", color: "#0A66C2", label: LinkedIn, link: "https://www.linkedin.com/in/joe-mccann-dev/"}
- {icon: "ion-logo-github", color: "#3b3f44", label: GitHub, link: "https://github.com/joe-mccann-dev"}



# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: joe.mccann@mailbox.org # Add your email for contact form
  description: I'd love to hear from you! <a href="mailto:joe.mccann@mailbox.org">Send me an email</a> or fill out the form below.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: joe-mccann-dev # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.