#-------------------------------
# Site Settings
title: joe-mccann.dev
logo: # You can add own logo. For example '/images/logo.png'.
author: Joe McCann
description: Full Stack Developer based in the Boston area.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Resume'
      url: '/resume/'

#-------------------------------
# Hero Settings
hero:
  hero__title: Hi there, my name's Joe. I'm a Full Stack Developer based in New England.
  hero__description: I'm a self-taught programmer and software enthusiast. About two years ago, I discovered a love of programming. I've since been building rewarding projects and git committing frequently. When I'm not debugging or writing specs, I enjoy playing guitar and bass, discovering new music, and running or hiking the trails of New England. Please feel free to check out the projects in my <a href="#portfolio">portfolio</a>.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__projects:
    - image: /images/gembook.png
      title: Gembook
      summary: A social media capstone project completed as part of The Odin Project’s Ruby on Rails curriculum.
      demo: <a href="https://fathomless-citadel-41420.herokuapp.com/">Gembook</a>
      repo: <a href="https://github.com/joe-mccann-dev/gembook">View on GitHub</a>
      description:
        - Programmed all core functionality of a sensible social media site, including friendships, profiles, posts, comments, nested comments, and likes.
        - Streamlined authentication process-- clients can log in with either email or via OAuth.
        - Tested application thoroughly with the testing tool RSpec, including system and unit specs.
    
    - image: /images/chess.png
      title: Ruby Chess
      summary: Conceptualized a fully functional and featured command line chess game using object-oriented concepts such as inheritance and composition.
      demo: <a href="https://replit.com/@JoeMcCannDev/chess#README.md">Ruby Chess</a>
      repo: <a href="https://github.com/joe-mccann-dev/chess">View on GitHub</a>
      description:
        - Debugged and troubleshot issues with pry-byebug.
        - Arranged for serialization of game objects, allowing for easy in-game saving and loading.
      
    - image: /images/movie-buddy-screenshot.png
      title: Movie Buddy
      summary: Sinatra web app that submits requests to the OMDb API and returns movies based on title and release year parameters.
      demo: <a href="https://movie-buddy.onrender.com/">Movie Buddy</a>
      repo: <a href="https://github.com/joe-mccann-dev/MovieBuddy">View on GitHub</a>
      description:
        - Designed Ruby objects to interact with a public database.
        - Arranged for parallel API requests and caching with the Typhoeus gem to improve performance.
      
#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com/joe_mccann_dev"}
- {icon: "ion-logo-linkedin", color: "#0A66C2", label: LinkedIn, link: "https://www.linkedin.com/in/joe-mccann-dev/"}
- {icon: "ion-logo-github", color: "#3b3f44", label: GitHub, link: "https://github.com/joe-mccann-dev"}



# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: joe.mccann@mailbox.org # Add your email for contact form
  description: I'd love to hear from you! <a href="mailto:joe.mccann@mailbox.org">Send me an email</a> or fill out the form below.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: joe-mccann-dev # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.